### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by joshblack** [joshblack/pkg#1]
```[tasklist]
### Tasks
- [ ] A `resolve` helper
- [ ] A `dependency-graph` helper
- [ ] A package exports helper
- [ ] A package exports size diff helper
- [ ] A workspaces explorer to view the workspaces in a project
```
